# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5) 

In [3]:
print(A) 
print(f"Number of axes =", A.ndim) 
print(f"The shape of A =", A.shape) 
print(f"The size (amount of elements) in A =", A.size) 
print(f"A's datatype =", A.dtype) 

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
Number of axes = 2
The shape of A = (3, 5)
The size (amount of elements) in A = 15
A's datatype = int32


### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)  
C = np.ones((3, 3))*2 

In [5]:
B - C

array([[-1.,  0.,  1.],
       [ 2.,  3.,  4.],
       [ 5.,  6.,  7.]])

In [6]:
B * C

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.],
       [14., 16., 18.]])

In [7]:
B @ C

array([[12., 12., 12.],
       [30., 30., 30.],
       [48., 48., 48.]])

### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [8]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [9]:
np.exp(B)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [10]:
B.min()

1

In [11]:
B.min(axis=1)

array([1, 4, 7])

In [12]:
B.min(axis=0)

array([1, 2, 3])

In [13]:
np.argmin(B)

0

In [14]:
np.argmin(B, axis=1)

array([0, 0, 0], dtype=int64)

In [15]:
B.sum()

45

In [16]:
np.mean(B, axis=0)

array([4., 5., 6.])

In [17]:
np.median(B, axis=0)

array([4., 5., 6.])

### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [18]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [19]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

When fewer indices are provided than the number of axes, the missing indices are considered complete slices, and you will get the whole row with all the column values for that row - like above. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [20]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [21]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [22]:
for element in A.flat:
    print(element)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [24]:
a = np.arange(30)            # it creates a flat array a with all numbers in one row from 0 up to 29
b = a.reshape((2, 3, -1))    # it creates the array b from the array a's values and presents them with 3 dimensions. 
                             # 2 arrays each with 3 rows and 5 columns each
                             # we can write -1 because the numbers of columns is determined by the two other set dimensions
print(a)                     # we print the original flat array
print()                      # print a space
print(b)                     # we print array b with a's values in three dimensions

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [25]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1 + m2)

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [26]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [27]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

print( A + b)

[[1 2]
 [3 4]]
[2 2]
[[3 4]
 [5 6]]


# Linear Algebra Exercises

The exercies are taken from the "Matrix Algebra for Engineers" by Chasnov: https://www.math.hkust.edu.hk/~machas/matrix-algebra-for-engineers.pdf .

Do the following exercises: 
* Chapter 2, exercise 1-3.
* Quiz on p.11, exercise 2.  (p. 8 ?)
* Chapter 6, exercise 1. 
* Quiz on p.19, exercise 3. 


* Chapter 10, exercise 1. 
* Chapter 12 exercise 1. 


In [28]:
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])

C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])

E = np.array([[1], [2]])

print(A)
print(B)
print(C)
print(D)
print(E)

[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]


**Chap2. Question 1.**

**Write a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In this exercise, create a function that takes two matrices as input and either adds or multiplies them by specifying a argument as either 'add' or 'multiply'. Validate that both matrices taken as input are of the type ndarray (use the isinstance function).

In [32]:
def add_mult_matrices(a, b, operation): 
    
    if not isinstance(a, np.ndarray) or not isinstance(b, np.ndarray): 
        raise TypeError ("Both arrays should be of the type nparrays")
    else:
        if operation == "add":                      
            if a.shape == b.shape:                   
                return a + b
            else:
                return ("Can not compute: The arrays should be of the same size")
        elif operation == "multiply":                    
            if a.shape[1] == b.shape[0]:                                                 
                return a @ b                        
            else: 
                return "Can not compute: Number of columns in array does not equal rows in array 2"       

In [33]:
# Compute if defined: B − 2A, 3C − E, AC, CD, CB

print(f"B-2A = \n ",add_mult_matrices(B, -2*A, "add"))
print(f"3C-1E = \n ",add_mult_matrices(3*C, -1*E, "add"))  
print(f"A*C = \n ",add_mult_matrices(A, C, "multiply"))
print(f"C*D = \n ",add_mult_matrices(C, D, "multiply"))
print(f"C*B = \n ",add_mult_matrices(C, B, "multiply"))   

B-2A = 
  [[ 0 -4  3]
 [ 0 -2 -4]]
3C-1E = 
  Can not compute: The arrays should be of the same size
A*C = 
  Can not compute: Number of columns in array does not equal rows in array 2
C*D = 
  [[11 10]
 [10 11]]
C*B = 
  [[  8 -10  -3]
 [ 10  -8   0]]


**Chap2. Question 2**   -     Verify that AB = AC and yet B ̸= C

In [34]:
A = np.array([[1, 2], [2, 4]])  
B = np.array([[2, 1], [1, 3]])
C = np.array([[4, 3], [0, 2]])

if np.array_equal(A @ B, A @ C):
    print("AB are equal to AC")
else:
    print("Not equal")
print(A @ B)
print(A @ C)
print()
if np.array_equal(B, C):
    print("B and C are the same")
else:
    print("And yet, B and C are not the same")
print(B)
print(C)

AB are equal to AC
[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]

And yet, B and C are not the same
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]


**Chap2. Question 3**    - Compute AD and DA

In [35]:
A = np.array([[1, 1, 1], [1, 2, 3],  [1, 3, 4]])  
D = np.array([[2, 0, 0], [0, 3, 0],  [0, 0, 4]])

print(A @ D)               
print()
print(D @ A)

[[ 2  3  4]
 [ 2  6 12]
 [ 2  9 16]]

[[ 2  2  2]
 [ 3  6  9]
 [ 4 12 16]]


**Quiz p.11, Question 2** - p.8 - What are the matrix product A1*A2 equal to

In [36]:
A1 = np.array([[1, -1], [-1, 1]])            
A2 = np.array([[-1, 1], [1, -1]])

a = np.array([[-2, 2], [2, -2]])
b = np.array([[2, -2], [-2, 2]])
c = np.array([[-2, 2], [-2, 2]])
d = np.array([[-2,-2], [2, 2]])
array_list = {'a': a, 'b': b, 'c': c, 'd': d}

for array in array_list: 
    if np.all(A1 @ A2 == array_list[array]):
        print (f"The matrix product of A1*A2 are equal to the array, {array}, in array_list")


The matrix product of A1*A2 are equal to the array {'a'} in array_list


**Chap 6. Question 1**- Find the inverses of the matrices

In [37]:
A = np.array([[5, 6], [4, 5]])             
B = np.array([[6, 4], [3, 3]])
 
if np.linalg.det(A) !=0:
    print(f"The inverse of A is \n", np.linalg.inv(A))
else:
   "Inverse doesn't exist"

if np.linalg.det(B) !=0:
    print(f"The inverse of B is \n", np.linalg.inv(B))
else:
   "Inverse doesn't exist"

The inverse of A is 
 [[ 5. -6.]
 [-4.  5.]]
The inverse of B is 
 [[ 0.5        -0.66666667]
 [-0.5         1.        ]]


**Quiz p.19, Question 3** p 15  - Which matrix is the inverse of A  

In [41]:
A = np.array([[2, 2], [1, 2]])                      

a = np.array([[2, -2], [-1, 2]]) 
b = np.array([[-2, 2], [1, -2]]) 
c = np.array([[2, 2], [-1, -2]]) 
d = np.array([[-2, -2], [1, 2]]) 
array_list = {'a': a, 'b': b, 'c': c, 'd': d}

for array in array_list: 
    if np.allclose(np.linalg.inv(A), (0.5*array_list[array])):
        print(f"The inverse version of A is equal to {array} in array_list")

The inverse version of A is equal to a in array_list


**Chap10. Question 1 a)** - Using Gaussian elimination with back substitution, solve the following equations

In [45]:
# (x1 −7x2 −2x3 = −7,)
# (−3x1 + 5x2 + x3 = 5,)
# (6x1 − 4x2 = 2.)
   
def RowScale(A,i,scale):                 # RowScale will return duplicate array with the entries of row k multiplied by scale
    B = np.copy(A).astype('float64')
    B[i, :] *= scale
    return B

def RowAdd(A,i,j,scale):                 # RowAdd will return a duplicate array where row i is added with a scaled row j
    B = np.copy(A).astype('float64')    
    scaled_row_j = B[j, :] * scale      
    B[i, :] = B[i, :] + scaled_row_j   
    return B                             

A = np.array([[3, -7, -2, -7], [-3, 5, +1, 5],  [6, -4, 0, 2]])
print(f"Array based on the equations \n", A)
print("Gauss elimination")
A1 = RowAdd(A,1,0,1)
print(A1)
A2 = RowAdd(A1,2,0,-2)
print(A2)
A3 = RowAdd(A2,2,1,5)
print(f"The array in upper triangle form \n",A3)

# Back substitution function
def back_substitution(A, b):
    N = len(A)                                     # N counts the rumber of rows in the first array 3
    x = np.zeros(N)                                # makes an array for x with the same number of rows as the array A 
    
    for i in range(N-1,-1,-1):                     # iterates over the rows in reverse order from row 2 to 0 (ex. -1) one step
        s = A[i,:] @ x                             # matrix multiplication for i'th row with x
        if A[i,i] == 0:                            # checks if our determinant is zero
            raise ValueError("Division with zero not allowed")
        else:
            x[i] = (b[i] - s) / A[i,i]             # calculates x from last row and upwwards
    return x

# Change array to this form Ax=b (x is located in the back substition function)
A4 = A3[:,0:3]
a = A3[:,-1]

solution_a = back_substitution(A4, a)
print(f"Solution: x =", solution_a)  

Array based on the equations 
 [[ 3 -7 -2 -7]
 [-3  5  1  5]
 [ 6 -4  0  2]]
Gauss elimination
[[ 3. -7. -2. -7.]
 [ 0. -2. -1. -2.]
 [ 6. -4.  0.  2.]]
[[ 3. -7. -2. -7.]
 [ 0. -2. -1. -2.]
 [ 0. 10.  4. 16.]]
The array in upper triangle form 
 [[ 3. -7. -2. -7.]
 [ 0. -2. -1. -2.]
 [ 0.  0. -1.  6.]]
Solution: x = [ 3.  4. -6.]


**Chap10. Question 1 b)**

In [46]:
# x1 − 2x2 + 3x3 = 1,
# −x1 + 3x2 − x3 = −1,
# 2x1 − 5x2 + 5x3 = 1.

B = np.array([[1, -2, 3, 1], [-1, 3, -1, -1],  [2, -5, 5, 1]])
print(f"Array based on the equations \n", A)

print("Gauss elimination")
B1 = RowAdd(B,1,0,1)
print(B1)
B2 = RowAdd(B1,2,0,-2)
print(B2)
B3 = RowAdd(B2,2,1,1)
print(f"Array in upper triangle form \n", B3)

# Change array to this form Ax=b (x is located in the back substition function)
B4 = B3[:,0:3]
b = B3[:,-1]

# back substitution
solution_b = back_substitution(B4, b)
print(f"Solution: x =", solution_b)

Array based on the equations 
 [[ 3 -7 -2 -7]
 [-3  5  1  5]
 [ 6 -4  0  2]]
Gauss elimination
[[ 1. -2.  3.  1.]
 [ 0.  1.  2.  0.]
 [ 2. -5.  5.  1.]]
[[ 1. -2.  3.  1.]
 [ 0.  1.  2.  0.]
 [ 0. -1. -1. -1.]]
Array in upper triangle form 
 [[ 1. -2.  3.  1.]
 [ 0.  1.  2.  0.]
 [ 0.  0.  1. -1.]]
Solution: x = [ 8.  2. -1.]


**Chap 12. Question 1** - Compute the inverse of A

In [52]:
C = np.array([[3, -7, -2, 1, 0, 0], [-3, 5, 1, 0, 1, 0], [6, -4, 0, 0, 0, 1]])
print(f"Original array \n {C}")

print("Gauss elimination")
C1 = RowAdd(C,1,0,1)
print(C1)
C2 = RowAdd(C1,2,0,-2)
print(C2)
C3 = RowAdd(C2,2,1,5)
print(C3)
C4 = RowAdd(C3,0,1,-3.5)
print(C4)
C5 = RowAdd(C4,1,2,-1)
print(C5)
C6 = RowAdd(C5,0,2,1.5)
print(C6)
C7 = RowScale(C6,2,-1)
print(C7)
C8 = RowScale(C7,1,-0.5)
print(C8)
C9 = RowScale(C8,0,1/3)
print(C9)
print()

Ci = np.copy(C9[:, 3:])
print(f"The inverse array of C is \n", Ci)

Original array 
 [[ 3 -7 -2  1  0  0]
 [-3  5  1  0  1  0]
 [ 6 -4  0  0  0  1]]
Gauss elimination
[[ 3. -7. -2.  1.  0.  0.]
 [ 0. -2. -1.  1.  1.  0.]
 [ 6. -4.  0.  0.  0.  1.]]
[[ 3. -7. -2.  1.  0.  0.]
 [ 0. -2. -1.  1.  1.  0.]
 [ 0. 10.  4. -2.  0.  1.]]
[[ 3. -7. -2.  1.  0.  0.]
 [ 0. -2. -1.  1.  1.  0.]
 [ 0.  0. -1.  3.  5.  1.]]
[[ 3.   0.   1.5 -2.5 -3.5  0. ]
 [ 0.  -2.  -1.   1.   1.   0. ]
 [ 0.   0.  -1.   3.   5.   1. ]]
[[ 3.   0.   1.5 -2.5 -3.5  0. ]
 [ 0.  -2.   0.  -2.  -4.  -1. ]
 [ 0.   0.  -1.   3.   5.   1. ]]
[[ 3.   0.   0.   2.   4.   1.5]
 [ 0.  -2.   0.  -2.  -4.  -1. ]
 [ 0.   0.  -1.   3.   5.   1. ]]
[[ 3.   0.   0.   2.   4.   1.5]
 [ 0.  -2.   0.  -2.  -4.  -1. ]
 [-0.  -0.   1.  -3.  -5.  -1. ]]
[[ 3.   0.   0.   2.   4.   1.5]
 [-0.   1.  -0.   1.   2.   0.5]
 [-0.  -0.   1.  -3.  -5.  -1. ]]
[[ 1.          0.          0.          0.66666667  1.33333333  0.5       ]
 [-0.          1.         -0.          1.          2.          0.5       ]
 [-0.

½### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [53]:
v1 = np.arange(4)
v2 = v1[-2:]   
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [54]:
# The base attribute of a view returns the original array while it returns None for a copy.
# print(v1.base)
# print(v2.base)

if v1.base is None:                               
    print("v1.base = none - v1 is an original")
else:
    print("v1.base = an array - v1 is a view")
        
if v2.base is None:
    print("v2.base = none - v2 is an original")
else:
    print("v2.base does not equal none - v2 is a view")

v1.base = none - v1 is an original
v2.base does not equal none - v2 is a view


In [55]:
# We change the last element in v2
v2[-1] = 123
print(f"v2 array =", v2)         
# We check that v1 has changed as well
print(f"v1 array =", v1)
print("v2 is only a view, therefore changes applied to v2 will change the original as well.")
print("And changes to v1 will change the view")

v2 array = [  2 123]
v1 array = [  0   1   2 123]
v2 is only a view, therefore changes applied to v2 will change the original as well.
And changes to v1 will change the view
